-- ============================================================
-- QUESTION BANK SEED DATA — Part 1: Indian Companies
-- Run after question_bank_schema.sql
-- ============================================================

-- FLIPKART (20 questions)
INSERT INTO company_questions (company, company_logo_url, difficulty, category, topic, question_text, expected_answer, hints, frequency, last_seen, upvotes, is_verified) VALUES
('Flipkart', 'https://logo.clearbit.com/flipkart.com', 'Medium', 'DSA', 'Arrays', 'Given an array of integers, find the length of the longest subarray with sum equal to K.', 'Use a hash map to store prefix sums. For each index, compute prefix sum and check if (prefix_sum - K) exists in the map. Time: O(n), Space: O(n).', '["Think about prefix sums — how can cumulative sums help?", "Use a hash map to store the first occurrence of each prefix sum.", "For each index i, check if prefix_sum[i] - K exists in the map. The difference in indices gives the subarray length."]', 'Very Common', 'Feb 2025', 142, true),
('Flipkart', 'https://logo.clearbit.com/flipkart.com', 'Hard', 'DSA', 'Dynamic Programming', 'Given a matrix of 0s and 1s, find the size of the largest square sub-matrix of all 1s.', 'Use DP where dp[i][j] = min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1]) + 1 if matrix[i][j] == 1. Track the maximum value. Time: O(m*n), Space: O(m*n).', '["Think about building squares bottom-up from smaller squares.", "dp[i][j] represents the side length of the largest square ending at (i,j).", "The value depends on three neighbors: top, left, and top-left diagonal."]', 'Common', 'Jan 2025', 98, true),
('Flipkart', 'https://logo.clearbit.com/flipkart.com', 'Medium', 'DSA', 'Trees', 'Given a binary tree, return the vertical order traversal of its nodes values.', 'Use BFS with a queue storing (node, horizontal_distance). Group nodes by horizontal distance using a TreeMap. Process level by level. Time: O(n log n).', '["Assign horizontal distances: root=0, left=hd-1, right=hd+1.", "Use BFS to maintain level order within each vertical line.", "A TreeMap/sorted map helps iterate columns left to right."]', 'Very Common', 'Mar 2025', 167, true),
('Flipkart', 'https://logo.clearbit.com/flipkart.com', 'Hard', 'System Design', 'System Design', 'Design a real-time inventory management system for Flipkart that handles flash sales with millions of concurrent users.', 'Use event-driven architecture with Kafka for order events. Redis for real-time inventory counts with atomic decrements. Database sharding by product category. Circuit breakers for flash sale traffic. Pre-warm caches before sales. Use optimistic locking for inventory updates.', '["Consider what happens when 1M users try to buy the same item simultaneously.", "Think about caching layers — where does the source of truth live?", "How do you prevent overselling while maintaining low latency?"]', 'Very Common', 'Feb 2025', 203, true),
('Flipkart', 'https://logo.clearbit.com/flipkart.com', 'Medium', 'DSA', 'Graphs', 'Find the shortest path in a weighted graph with non-negative weights using Dijkstra algorithm.', 'Use a min-heap (priority queue) initialized with source node (distance 0). For each node, relax all adjacent edges. Track visited nodes to avoid reprocessing. Time: O((V+E) log V).', '["Use a priority queue to always process the nearest unvisited node.", "Relaxation: if dist[u] + weight(u,v) < dist[v], update dist[v].", "Mark nodes as visited after processing to avoid cycles."]', 'Common', 'Jan 2025', 89, true),
('Flipkart', 'https://logo.clearbit.com/flipkart.com', 'Easy', 'DSA', 'Strings', 'Check if two strings are anagrams of each other.', 'Use a frequency count array of size 26. Increment for first string, decrement for second. If all counts are zero, they are anagrams. Time: O(n), Space: O(1).', '["Count character frequencies in both strings.", "Use a single array — increment for one string, decrement for the other.", "If all values are 0 at the end, the strings are anagrams."]', 'Very Common', 'Mar 2025', 56, true),
('Flipkart', 'https://logo.clearbit.com/flipkart.com', 'Hard', 'DSA', 'Dynamic Programming', 'Given a string, find the minimum number of cuts needed to partition it such that every substring is a palindrome.', 'Use DP: let cuts[i] = min cuts for s[0..i]. Precompute a palindrome table isPalin[i][j]. For each i, if s[0..i] is palindrome, cuts[i]=0; else try all j<i where s[j+1..i] is palindrome and minimize cuts[j]+1. Time: O(n²).', '["First precompute which substrings are palindromes using a 2D table.", "cuts[i] = minimum cuts for the first i+1 characters.", "For each position, try all possible last palindrome partitions."]', 'Common', 'Dec 2024', 112, true),
('Flipkart', 'https://logo.clearbit.com/flipkart.com', 'Medium', 'System Design', 'System Design', 'Design a product search and recommendation engine for an e-commerce platform.', 'Use Elasticsearch for full-text search with fuzzy matching. Implement collaborative filtering for recommendations. Use Redis to cache popular searches. Event sourcing for user behavior tracking. ML pipeline for personalized rankings using user purchase history and browsing patterns.', '["How would you handle typos and fuzzy matching in search?", "Think about personalization — how do you rank results differently per user?", "Consider cold-start problem for new users with no history."]', 'Very Common', 'Jan 2025', 178, true),
('Flipkart', 'https://logo.clearbit.com/flipkart.com', 'Medium', 'DSA', 'Arrays', 'Trapping Rain Water: Given n non-negative integers representing an elevation map, compute how much water it can trap after raining.', 'Use two-pointer approach. Maintain left_max and right_max. Water at each position = min(left_max, right_max) - height[i]. Time: O(n), Space: O(1).', '["Water above each bar depends on the tallest bars to its left and right.", "For each position: water = min(max_left, max_right) - height.", "Two pointers from both ends avoid needing extra arrays for max values."]', 'Very Common', 'Mar 2025', 234, true),
('Flipkart', 'https://logo.clearbit.com/flipkart.com', 'Medium', 'DSA', 'Linked Lists', 'Detect and remove a cycle in a linked list.', 'Use Floyd''s cycle detection (slow/fast pointers). Once cycle detected, reset slow to head. Move both one step at a time — they meet at cycle start. Set the node before the meeting point''s next to null. Time: O(n), Space: O(1).', '["Use two pointers: slow moves 1 step, fast moves 2 steps.", "If they meet, a cycle exists. Reset one pointer to head.", "Move both one step at a time — they meet at cycle start."]', 'Common', 'Feb 2025', 76, true),
('Flipkart', 'https://logo.clearbit.com/flipkart.com', 'Hard', 'System Design', 'System Design', 'Design a notification system that can send 100M+ notifications per day across push, SMS, and email channels.', 'Use a message queue (Kafka) to decouple. Separate services per channel. Priority queues for urgent notifications. Rate limiting per user. Template engine for content. Dead letter queue for failures. Idempotency keys to prevent duplicates. Analytics pipeline for delivery tracking.', '["How do you handle different channels with different latency requirements?", "Think about rate limiting — you don''t want to spam users.", "What happens when a notification fails? Retry strategy?"]', 'Common', 'Jan 2025', 145, true),
('Flipkart', 'https://logo.clearbit.com/flipkart.com', 'Easy', 'DSA', 'Stacks', 'Implement a stack that supports push, pop, top, and retrieving the minimum element in constant time.', 'Use two stacks: main stack and min stack. On push, push to main; if value <= min stack top, push to min stack too. On pop, if popped value equals min stack top, pop min stack too. All operations O(1).', '["You need O(1) for getMin — a regular stack won''t suffice.", "Consider maintaining a parallel stack that tracks minimums.", "Push to min stack only when new value is <= current minimum."]', 'Very Common', 'Mar 2025', 67, true),
('Flipkart', 'https://logo.clearbit.com/flipkart.com', 'Medium', 'DSA', 'Trees', 'Serialize and deserialize a binary tree.', 'Use preorder traversal for serialization, using a delimiter and null markers. For deserialization, split the string and rebuild the tree recursively using a queue/index. Time: O(n), Space: O(n).', '["Preorder traversal naturally captures tree structure.", "Use a special marker (like ''#'') for null nodes.", "Deserialization: consume tokens one by one, building left then right subtrees."]', 'Common', 'Feb 2025', 91, true),
('Flipkart', 'https://logo.clearbit.com/flipkart.com', 'Medium', 'HR', 'Behavioral', 'Tell me about a time you had to make a critical decision with incomplete information. How did you approach it?', 'A strong answer uses the STAR format: describe the Situation with unclear data, the Task you needed to accomplish, the Action you took (e.g., gathering available data, consulting stakeholders, making a calculated risk), and the Result. Emphasize learning from outcomes and adaptability.', '["Use the STAR format to structure your answer.", "Focus on your decision-making framework, not just the outcome.", "Show that you can act despite uncertainty while managing risk."]', 'Common', 'Jan 2025', 45, true),
('Flipkart', 'https://logo.clearbit.com/flipkart.com', 'Hard', 'DSA', 'Graphs', 'Find all strongly connected components in a directed graph.', 'Use Kosaraju''s or Tarjan''s algorithm. Kosaraju''s: (1) Fill a stack by finish times using DFS, (2) Transpose the graph, (3) Pop from stack and do DFS on transposed graph — each DFS yields one SCC. Time: O(V+E).', '["A strongly connected component means every vertex is reachable from every other.", "Kosaraju''s uses two DFS passes and a transposed graph.", "Tarjan''s uses a single DFS with a stack and low-link values."]', 'Rare', 'Nov 2024', 78, true),
('Flipkart', 'https://logo.clearbit.com/flipkart.com', 'Medium', 'DSA', 'Heaps', 'Find the Kth largest element in an unsorted array.', 'Use a min-heap of size K. Iterate through array: if heap size < K, push. If current element > heap top, pop and push. Final heap top is the Kth largest. Time: O(n log K). Alternatively, use QuickSelect for average O(n).', '["A min-heap of size K always keeps the K largest elements.", "Compare each new element with the heap''s minimum.", "QuickSelect is another approach with average O(n) time."]', 'Very Common', 'Mar 2025', 134, true),
('Flipkart', 'https://logo.clearbit.com/flipkart.com', 'Easy', 'HR', 'Behavioral', 'Why do you want to work at Flipkart?', 'Mention Flipkart''s impact on Indian e-commerce, the engineering scale (millions of users, complex logistics), interest in solving real-world problems at scale, and alignment with your career goals. Reference specific Flipkart tech blog posts or products that excite you.', '["Research Flipkart''s recent initiatives and tech stack.", "Connect your skills and interests to Flipkart''s engineering challenges.", "Show genuine enthusiasm — mention specific products or features you admire."]', 'Very Common', 'Mar 2025', 34, true),
('Flipkart', 'https://logo.clearbit.com/flipkart.com', 'Hard', 'DSA', 'Dynamic Programming', 'Given a set of items with weights and values, and a knapsack capacity, find the maximum value that can be obtained. (0/1 Knapsack)', 'Use 2D DP: dp[i][w] = max value using first i items with capacity w. dp[i][w] = max(dp[i-1][w], dp[i-1][w-wt[i]] + val[i]) if wt[i] <= w. Space can be optimized to 1D. Time: O(n*W), Space: O(W).', '["For each item, you have two choices: include or exclude.", "dp[i][w] = max(exclude item i, include item i if it fits).", "Can optimize to 1D array by iterating capacity backwards."]', 'Very Common', 'Feb 2025', 156, true),
('Flipkart', 'https://logo.clearbit.com/flipkart.com', 'Medium', 'System Design', 'System Design', 'Design a URL shortener like bit.ly.', 'Use Base62 encoding of an auto-incrementing ID or a hash. Store mapping in a distributed key-value store (Redis + SQL). Use 301 redirects for caching. Handle collision with retry. Add analytics tracking clicks, geography, referrer. Rate limiting for API. CDN for redirect performance.', '["How do you generate short, unique keys? Consider Base62 encoding.", "Think about read-heavy workload — redirects happen far more than creates.", "How do you handle analytics and click tracking at scale?"]', 'Very Common', 'Mar 2025', 189, true),
('Flipkart', 'https://logo.clearbit.com/flipkart.com', 'Medium', 'DSA', 'Arrays', 'Given an array of intervals, merge all overlapping intervals.', 'Sort by start time. Iterate and merge: if current.start <= prev.end, merge by taking max(prev.end, current.end). Otherwise, add previous to result and move on. Time: O(n log n) for sort, O(n) for merge.', '["Sort intervals by start time first.", "Compare each interval''s start with the previous interval''s end.", "If overlapping, extend the end to max of both ends."]', 'Very Common', 'Mar 2025', 123, true);

-- PAYTM (15 questions)
INSERT INTO company_questions (company, company_logo_url, difficulty, category, topic, question_text, expected_answer, hints, frequency, last_seen, upvotes, is_verified) VALUES
('Paytm', 'https://logo.clearbit.com/paytm.com', 'Medium', 'DSA', 'Arrays', 'Find the maximum sum subarray (Kadane''s Algorithm).', 'Track current_sum and max_sum. At each element, current_sum = max(element, current_sum + element). Update max_sum = max(max_sum, current_sum). Time: O(n), Space: O(1).', '["At each position, decide: start a new subarray or extend the current one.", "current_sum resets to the element itself if adding it makes sum smaller.", "Keep tracking the global maximum across all positions."]', 'Very Common', 'Mar 2025', 198, true),
('Paytm', 'https://logo.clearbit.com/paytm.com', 'Medium', 'DSA', 'Strings', 'Find the longest palindromic substring in a given string.', 'Expand around center approach: for each index, expand outward while characters match. Check both odd and even length palindromes. Time: O(n²), Space: O(1). Manacher''s algorithm for O(n).', '["A palindrome expands equally from its center.", "Try each index (and each pair of adjacent indices) as potential centers.", "Expand outward while characters match and track the longest found."]', 'Very Common', 'Feb 2025', 167, true),
('Paytm', 'https://logo.clearbit.com/paytm.com', 'Hard', 'Backend', 'Concurrency', 'How would you design a thread-safe payment processing queue that ensures exactly-once processing?', 'Use an idempotency key per transaction. Distributed lock (Redis SETNX) before processing. Two-phase commit or saga pattern for multi-step payments. Persistent message queue (Kafka) with consumer group offsets for at-least-once, combined with idempotency check for exactly-once.', '["What does exactly-once mean in a distributed system?", "Think about idempotency — how do you detect duplicate requests?", "Consider: at-least-once delivery + idempotent processing = exactly-once semantics."]', 'Common', 'Jan 2025', 134, true),
('Paytm', 'https://logo.clearbit.com/paytm.com', 'Medium', 'DSA', 'Trees', 'Find the lowest common ancestor (LCA) of two nodes in a binary tree.', 'Recursive approach: if root is null or equals either node, return root. Recurse left and right. If both return non-null, root is LCA. If only one is non-null, return that one. Time: O(n), Space: O(h).', '["If the current node is one of the targets, it could be the LCA.", "If targets are found in different subtrees, current node is the LCA.", "If both are in the same subtree, LCA is deeper in that subtree."]', 'Very Common', 'Mar 2025', 145, true),
('Paytm', 'https://logo.clearbit.com/paytm.com', 'Medium', 'Backend', 'Database', 'Explain database indexing. When would you use a B-tree index vs a hash index?', 'B-tree indexes support range queries, ordering, and prefix matching — ideal for most use cases. Hash indexes are O(1) for exact lookups but don''t support ranges. B-trees are default in most RDBMS. Use hash indexes for equality-only lookups in memory stores like Redis.', '["Think about what operations each index type supports.", "B-trees maintain sorted order — what queries benefit from that?", "Hash indexes are fastest for exact match but limited in flexibility."]', 'Common', 'Feb 2025', 89, true),
('Paytm', 'https://logo.clearbit.com/paytm.com', 'Easy', 'DSA', 'Arrays', 'Two Sum: Given an array and a target, find two numbers that add up to the target.', 'Use a hash map. For each element, check if (target - element) exists in the map. If yes, return both indices. Otherwise, add current element to the map. Time: O(n), Space: O(n).', '["Brute force is O(n²) — can you do better?", "Use a hash map to store elements you''ve seen.", "For each element, check if its complement (target - element) exists in the map."]', 'Very Common', 'Mar 2025', 210, true),
('Paytm', 'https://logo.clearbit.com/paytm.com', 'Hard', 'DSA', 'Graphs', 'Implement a function to detect negative weight cycles in a graph using Bellman-Ford.', 'Run Bellman-Ford: relax all edges V-1 times. Then do one more pass — if any edge can still be relaxed, a negative cycle exists. Time: O(V*E). Track predecessor to reconstruct the cycle path if needed.', '["Bellman-Ford relaxes all edges V-1 times for shortest paths.", "After V-1 iterations, no further relaxation should be possible.", "If an edge can still be relaxed on the Vth pass, there''s a negative cycle."]', 'Common', 'Dec 2024', 67, true),
('Paytm', 'https://logo.clearbit.com/paytm.com', 'Medium', 'Backend', 'API Design', 'Design a RESTful API for a digital wallet service. Include endpoints for balance check, send money, and transaction history.', 'GET /wallet/balance — returns current balance. POST /wallet/transfer — body: {to_user_id, amount, idempotency_key}. GET /wallet/transactions?page=1&limit=20 — paginated history. Use JWT auth. Implement optimistic locking for balance updates. Return appropriate HTTP status codes.', '["Think about authentication and authorization for each endpoint.", "How do you prevent double-spending or duplicate transfers?", "Consider pagination for transaction history — users may have thousands."]', 'Very Common', 'Feb 2025', 112, true),
('Paytm', 'https://logo.clearbit.com/paytm.com', 'Medium', 'DSA', 'Dynamic Programming', 'Coin Change: Given coins of different denominations and a total amount, find the minimum number of coins needed.', 'Use DP: dp[i] = min coins to make amount i. Initialize dp[0]=0, rest=Infinity. For each amount, try all coins: dp[i] = min(dp[i], dp[i-coin]+1) for each coin <= i. Time: O(amount * coins), Space: O(amount).', '["dp[i] represents the minimum coins needed to make amount i.", "For each amount, try using each coin denomination.", "dp[i] = min(dp[i], dp[i - coin_value] + 1) if the coin fits."]', 'Very Common', 'Mar 2025', 178, true),
('Paytm', 'https://logo.clearbit.com/paytm.com', 'Medium', 'Backend', 'Caching', 'Implement an LRU Cache with O(1) get and put operations.', 'Use a doubly linked list + hash map. Map stores key → node reference. On get: move node to front. On put: add to front, if capacity exceeded, remove from tail. Doubly linked list enables O(1) removal and insertion.', '["You need O(1) for both get and put — what data structures support that?", "A hash map gives O(1) lookup, but how do you track recency?", "A doubly linked list allows O(1) removal and insertion at both ends."]', 'Very Common', 'Mar 2025', 189, true),
('Paytm', 'https://logo.clearbit.com/paytm.com', 'Easy', 'DSA', 'Linked Lists', 'Reverse a singly linked list.', 'Iterative: use three pointers (prev, curr, next). Traverse list, reversing each next pointer. Time: O(n), Space: O(1). Recursive: reverse rest of list, then point next node back. Time: O(n), Space: O(n) stack.', '["You need to reverse the direction of each pointer.", "Use prev, curr, and next pointers to avoid losing references.", "Process one node at a time: save next, point curr to prev, advance."]', 'Very Common', 'Mar 2025', 87, true),
('Paytm', 'https://logo.clearbit.com/paytm.com', 'Hard', 'Backend', 'Distributed Systems', 'How would you ensure data consistency in a distributed payment system with multiple microservices?', 'Use Saga pattern for distributed transactions. Each service publishes events. Compensating transactions for rollback. Idempotency keys prevent duplicates. Event sourcing for audit trail. Two-phase commit for critical atomic operations. Eventual consistency with conflict resolution.', '["Traditional ACID transactions don''t work across microservices.", "The Saga pattern breaks transactions into local transactions with compensating actions.", "How do you handle the case where a downstream service fails after an upstream commits?"]', 'Common', 'Jan 2025', 123, true),
('Paytm', 'https://logo.clearbit.com/paytm.com', 'Medium', 'DSA', 'Stacks', 'Evaluate a postfix (Reverse Polish Notation) expression.', 'Use a stack. Scan left to right: push numbers, on operator pop two operands, apply operator, push result. Final stack top is the answer. Time: O(n), Space: O(n).', '["Process tokens left to right.", "Numbers go on the stack, operators pop two values and push the result.", "The last value on the stack is the final answer."]', 'Common', 'Feb 2025', 56, true),
('Paytm', 'https://logo.clearbit.com/paytm.com', 'Medium', 'DSA', 'Sorting', 'Sort an array of 0s, 1s, and 2s without using any sorting algorithm (Dutch National Flag).', 'Three-pointer approach: low=0, mid=0, high=n-1. If arr[mid]==0: swap(arr[low], arr[mid]), low++, mid++. If arr[mid]==1: mid++. If arr[mid]==2: swap(arr[mid], arr[high]), high--. Time: O(n), Space: O(1).', '["You need three regions: 0s, 1s, and 2s.", "Use three pointers: low (boundary of 0s), mid (current), high (boundary of 2s).", "Process mid pointer and swap elements to their correct regions."]', 'Very Common', 'Mar 2025', 98, true),
('Paytm', 'https://logo.clearbit.com/paytm.com', 'Medium', 'Backend', 'System Design', 'Design a rate limiter for an API gateway.', 'Token bucket or sliding window algorithm. Redis for distributed counting. Key per user/IP. Token bucket: refill tokens at fixed rate, consume on request. Sliding window: count requests in current window. Return 429 Too Many Requests when exceeded. Headers: X-RateLimit-Remaining.', '["What algorithm would you use? Token bucket vs sliding window?", "How do you make it work across multiple server instances?", "Consider different rate limits for different API endpoints or user tiers."]', 'Common', 'Feb 2025', 134, true);
