-- ============================================================
-- SEED Part 2: Zomato, Swiggy, CRED, Razorpay
-- ============================================================

-- ZOMATO (15 questions)
INSERT INTO company_questions (company, company_logo_url, difficulty, category, topic, question_text, expected_answer, hints, frequency, last_seen, upvotes, is_verified) VALUES
('Zomato', 'https://logo.clearbit.com/zomato.com', 'Medium', 'DSA', 'Graphs', 'Given a grid representing a city map, find the shortest delivery route from a restaurant to a customer avoiding blocked roads.', 'Use BFS on the grid treating open cells as graph nodes. BFS guarantees shortest path in unweighted graphs. Time: O(m*n), Space: O(m*n). For weighted graphs (varying road times), use Dijkstra.', '["Model the city as a grid graph — each cell is a node.", "BFS finds shortest path in unweighted graphs.", "Mark blocked cells as visited before starting BFS."]', 'Very Common', 'Feb 2025', 156, true),
('Zomato', 'https://logo.clearbit.com/zomato.com', 'Hard', 'System Design', 'System Design', 'Design a food delivery tracking system that shows real-time delivery partner location to customers.', 'Use WebSocket connections for real-time updates. GPS data from delivery app → Kafka → Location Service → WebSocket push to customer. Store location history in time-series DB (InfluxDB). Redis for current location cache. Geofencing for arrival detection. ETA calculation using historical delivery data.', '["How do you push real-time updates to the customer?", "Think about the frequency of location updates vs bandwidth.", "How do you calculate accurate ETAs that update in real-time?"]', 'Very Common', 'Mar 2025', 198, true),
('Zomato', 'https://logo.clearbit.com/zomato.com', 'Medium', 'DSA', 'Arrays', 'Given restaurant ratings as an array, find the maximum average rating subarray of size K.', 'Sliding window: compute sum of first K elements. Slide window by subtracting element leaving and adding element entering. Track maximum average. Time: O(n), Space: O(1).', '["Use a sliding window of size K.", "Instead of recomputing sum each time, add new element and remove old.", "Track the maximum sum seen, then divide by K for average."]', 'Common', 'Jan 2025', 78, true),
('Zomato', 'https://logo.clearbit.com/zomato.com', 'Medium', 'DSA', 'Sorting', 'Given a list of orders with timestamps and preparation times, schedule orders to minimize total waiting time.', 'Sort by preparation time (Shortest Job First / SJF). This minimizes average waiting time. Use a priority queue if orders arrive dynamically. Time: O(n log n).', '["Think about which scheduling algorithm minimizes waiting time.", "Shortest Job First minimizes average waiting/turnaround time.", "For dynamic arrivals, use a priority queue sorted by preparation time."]', 'Common', 'Feb 2025', 89, true),
('Zomato', 'https://logo.clearbit.com/zomato.com', 'Hard', 'DSA', 'Graphs', 'Given N delivery locations and distances between them, find the optimal route to deliver to all locations (Travelling Salesman variant).', 'Use DP with bitmask: dp[mask][i] = min cost to visit all cities in mask, ending at i. Base: dp[1<<start][start]=0. Transition: dp[mask|(1<<j)][j] = min(dp[mask][i] + dist[i][j]). Time: O(2^n * n²). For large N, use approximation algorithms.', '["This is related to the Travelling Salesman Problem.", "DP with bitmask can solve for small N (up to ~20).", "For larger N, consider greedy nearest-neighbor or 2-opt heuristics."]', 'Rare', 'Nov 2024', 67, true),
('Zomato', 'https://logo.clearbit.com/zomato.com', 'Easy', 'DSA', 'Hashing', 'Find the first non-repeating character in a string.', 'Use a hash map to count frequencies, then iterate string again to find first char with count 1. Time: O(n), Space: O(1) since alphabet is fixed-size.', '["Count frequency of each character first.", "Then scan the string again left to right.", "Return the first character with frequency exactly 1."]', 'Very Common', 'Mar 2025', 45, true),
('Zomato', 'https://logo.clearbit.com/zomato.com', 'Medium', 'System Design', 'System Design', 'Design a restaurant recommendation system based on user preferences, location, and past orders.', 'Collaborative filtering for similar users. Content-based filtering for cuisine preferences. Location-aware ranking using geo-indexes. Feature engineering: ratings, order frequency, cuisine tags, price range. A/B testing framework for ranking algorithms. Cold start: use popular restaurants in area.', '["How do you combine user preferences with location data?", "Think about collaborative vs content-based filtering.", "How do you handle new users with no order history (cold start)?"]', 'Common', 'Jan 2025', 134, true),
('Zomato', 'https://logo.clearbit.com/zomato.com', 'Medium', 'DSA', 'Trees', 'Given a BST, find the Kth smallest element.', 'In-order traversal of BST gives sorted order. Do in-order traversal, decrement K at each node. When K reaches 0, return current node. Time: O(H + K) where H is height. Can augment BST with subtree sizes for O(H).', '["In-order traversal of a BST visits nodes in ascending order.", "Count nodes as you traverse — stop at the Kth node.", "For repeated queries, augment each node with left subtree size."]', 'Very Common', 'Mar 2025', 112, true),
('Zomato', 'https://logo.clearbit.com/zomato.com', 'Medium', 'DSA', 'Dynamic Programming', 'Given a matrix, find the path from top-left to bottom-right with minimum sum. You can only move right or down.', 'DP: dp[i][j] = grid[i][j] + min(dp[i-1][j], dp[i][j-1]). Initialize first row and column as cumulative sums. Time: O(m*n), Space: O(m*n), can optimize to O(n).', '["Each cell can only be reached from the left or from above.", "dp[i][j] = cost of current cell + minimum of top and left.", "Initialize edges since they only have one possible path."]', 'Common', 'Feb 2025', 87, true),
('Zomato', 'https://logo.clearbit.com/zomato.com', 'Hard', 'System Design', 'System Design', 'Design a surge pricing system for food delivery that adjusts prices based on demand, supply, and external factors.', 'Collect real-time signals: order volume, active delivery partners, weather, time of day, area demand. ML model to predict surge multiplier. Redis for real-time demand counters per zone. Cap maximum surge. Gradual ramp-up/down. A/B test impact on order volume and partner availability.', '["What signals indicate high demand? Orders per minute, partner availability?", "How do you divide the city into pricing zones?", "How do you balance revenue with customer satisfaction?"]', 'Rare', 'Dec 2024', 98, true),
('Zomato', 'https://logo.clearbit.com/zomato.com', 'Easy', 'DSA', 'Arrays', 'Rotate an array by K positions to the right.', 'Reverse entire array, then reverse first K elements, then reverse remaining. Time: O(n), Space: O(1). Alternative: use extra array. Handle K > n by K = K % n.', '["Handle K > array length by taking K % n.", "The reversal approach uses three reverses with O(1) space.", "Reverse all, then reverse first K, then reverse rest."]', 'Very Common', 'Mar 2025', 56, true),
('Zomato', 'https://logo.clearbit.com/zomato.com', 'Medium', 'DSA', 'Hashing', 'Group anagrams from a list of strings.', 'Sort each string to create a key, group by sorted key using a hash map. Time: O(n * k log k) where k is max string length. Alternative: use character count as key for O(n * k).', '["Anagrams produce the same result when sorted.", "Use sorted string as a hash map key.", "Group all strings with the same key together."]', 'Very Common', 'Feb 2025', 134, true),
('Zomato', 'https://logo.clearbit.com/zomato.com', 'Medium', 'DSA', 'Graphs', 'Check if a given graph is bipartite.', 'Use BFS/DFS coloring. Assign two colors alternately. If a neighbor has the same color as current node, graph is not bipartite. Time: O(V+E). Works for disconnected graphs by checking all components.', '["Try coloring nodes with two colors such that no adjacent nodes share a color.", "Use BFS and assign alternating colors level by level.", "If you find a conflict (same color neighbors), it''s not bipartite."]', 'Common', 'Jan 2025', 78, true),
('Zomato', 'https://logo.clearbit.com/zomato.com', 'Medium', 'System Design', 'System Design', 'Design a review and rating system for restaurants with fraud detection.', 'Store reviews with user_id, restaurant_id, rating, text, timestamp. Aggregate ratings with weighted average (recent reviews weighted more). Fraud detection: ML model checking patterns (burst of 5-star, similar text, new accounts). Flag suspicious reviews for manual review. Rate limit reviews per user per restaurant.', '["How do you calculate a fair average rating?", "What patterns indicate fake reviews?", "How do you handle a restaurant owner posting fake reviews?"]', 'Common', 'Feb 2025', 89, true),
('Zomato', 'https://logo.clearbit.com/zomato.com', 'Medium', 'DSA', 'Strings', 'Implement a basic regex pattern matcher supporting . (any single char) and * (zero or more of preceding).', 'Use DP: dp[i][j] = true if s[0..i-1] matches p[0..j-1]. Handle * by checking zero occurrences (dp[i][j-2]) or one+ (dp[i-1][j] if chars match). Handle . as wildcard. Time: O(m*n).', '["''*'' means zero or more of the previous character.", "dp[i][j] represents whether s[0..i-1] matches pattern p[0..j-1].", "For ''*'': either skip the pattern pair (zero match) or consume a char (one+ match)."]', 'Rare', 'Nov 2024', 67, true);

-- SWIGGY (15 questions)
INSERT INTO company_questions (company, company_logo_url, difficulty, category, topic, question_text, expected_answer, hints, frequency, last_seen, upvotes, is_verified) VALUES
('Swiggy', 'https://logo.clearbit.com/swiggy.com', 'Medium', 'DSA', 'Stacks', 'Design a stack that supports getMin(), getMax(), push(), and pop() all in O(1) time.', 'Use three stacks: main, min-stack, max-stack. Push to min/max stacks when new value is ≤ current min or ≥ current max. Pop from auxiliary stacks when popped value equals their top. All operations O(1).', '["Extend the min-stack idea to also track maximum.", "Maintain two auxiliary stacks: one for mins, one for maxes.", "Push to auxiliary stacks only when the new value updates min/max."]', 'Common', 'Feb 2025', 98, true),
('Swiggy', 'https://logo.clearbit.com/swiggy.com', 'Medium', 'Backend', 'API Design', 'Design a RESTful API for an order management system with order placement, tracking, and cancellation.', 'POST /orders — place order with items, address, payment. GET /orders/:id — order details + status. PUT /orders/:id/cancel — cancel if status allows. GET /orders/:id/track — real-time status. Implement state machine: placed → confirmed → preparing → picked_up → delivered. Webhook for status updates.', '["Define clear order states and valid transitions.", "Not all orders can be cancelled — when should cancellation be blocked?", "How do you notify the user of status changes in real-time?"]', 'Very Common', 'Mar 2025', 145, true),
('Swiggy', 'https://logo.clearbit.com/swiggy.com', 'Hard', 'DSA', 'Graphs', 'Given N delivery locations with coordinates, assign M delivery partners to locations minimizing total distance covered.', 'Model as bipartite matching / assignment problem. Hungarian algorithm for optimal assignment in O(n³). For practical use, use K-means clustering to group nearby deliveries, then assign partners to clusters. Greedy nearest-neighbor as approximation.', '["This is an assignment problem — matching partners to deliveries.", "Hungarian algorithm gives optimal solution but is O(n³).", "For real-world scale, use clustering + greedy assignment as approximation."]', 'Rare', 'Nov 2024', 78, true),
('Swiggy', 'https://logo.clearbit.com/swiggy.com', 'Medium', 'DSA', 'Arrays', 'Find the maximum product subarray.', 'Track max_product and min_product at each position (min needed because negative × negative = positive). At each element: new_max = max(elem, max_prev * elem, min_prev * elem). Time: O(n), Space: O(1).', '["Negative numbers can become positive when multiplied by another negative.", "Track both maximum and minimum products ending at each position.", "At each element, the max could come from: the element itself, max*elem, or min*elem."]', 'Very Common', 'Mar 2025', 145, true),
('Swiggy', 'https://logo.clearbit.com/swiggy.com', 'Medium', 'Backend', 'Database', 'Explain the differences between SQL and NoSQL databases. When would you choose each?', 'SQL: structured data, ACID transactions, complex joins, fixed schema. Best for financial data, relational data. NoSQL: flexible schema, horizontal scaling, high throughput. Types: document (MongoDB), key-value (Redis), column-family (Cassandra), graph (Neo4j). Choose based on data model, scale, and consistency needs.', '["Think about the trade-offs: consistency vs availability vs partition tolerance (CAP).", "SQL excels at complex relationships and transactions.", "NoSQL excels at scale, flexibility, and specific access patterns."]', 'Very Common', 'Feb 2025', 112, true),
('Swiggy', 'https://logo.clearbit.com/swiggy.com', 'Easy', 'DSA', 'Queues', 'Implement a queue using two stacks.', 'Push stack and pop stack. Enqueue: push to push-stack. Dequeue: if pop-stack empty, transfer all from push-stack; then pop from pop-stack. Amortized O(1) per operation.', '["One stack for pushing, one for popping.", "Transfer elements only when the pop stack is empty.", "Each element is moved at most twice — amortized O(1)."]', 'Very Common', 'Mar 2025', 67, true),
('Swiggy', 'https://logo.clearbit.com/swiggy.com', 'Medium', 'Backend', 'Microservices', 'How would you decompose a monolithic food delivery application into microservices?', 'Identify bounded contexts: User Service, Restaurant Service, Order Service, Payment Service, Delivery Service, Notification Service. Use API Gateway for routing. Event-driven communication (Kafka) between services. Each service owns its database. Saga pattern for distributed transactions. Circuit breakers for resilience.', '["Identify independent business domains as service boundaries.", "How do services communicate? Sync (REST/gRPC) vs async (events)?", "Each service should own its data — no shared databases."]', 'Common', 'Jan 2025', 134, true),
('Swiggy', 'https://logo.clearbit.com/swiggy.com', 'Medium', 'DSA', 'Trees', 'Check if a binary tree is a valid BST.', 'In-order traversal should produce sorted sequence. Alternatively, recursive with range: each node must be within (min, max) bounds. Update bounds as you go left (max=node) or right (min=node). Time: O(n).', '["A valid BST has all left subtree values < node < all right subtree values.", "Pass valid range (min, max) down the tree recursively.", "Going left: update max to current node. Going right: update min."]', 'Very Common', 'Mar 2025', 123, true),
('Swiggy', 'https://logo.clearbit.com/swiggy.com', 'Hard', 'Backend', 'Distributed Systems', 'How would you design a distributed rate limiter that works across multiple API gateway instances?', 'Use Redis with atomic INCR + EXPIRE for sliding window. Token bucket with Redis: MULTI/EXEC for atomic token check and consume. Lua scripts for atomic operations. Sync across instances via shared Redis cluster. Consider local rate limiting + global sync for reduced latency.', '["Multiple gateway instances need shared state — where do you store it?", "Redis provides atomic operations — how do you use them for counting?", "Consider the trade-off between accuracy and latency of checking."]', 'Common', 'Jan 2025', 98, true),
('Swiggy', 'https://logo.clearbit.com/swiggy.com', 'Medium', 'DSA', 'Dynamic Programming', 'Longest Increasing Subsequence (LIS) — find the length of the longest strictly increasing subsequence.', 'DP approach: dp[i] = LIS ending at i. For each i, dp[i] = max(dp[j] + 1) for all j < i where arr[j] < arr[i]. Time: O(n²). Optimized with binary search + patience sorting: O(n log n).', '["dp[i] = length of LIS ending at index i.", "For each element, check all previous elements for valid extensions.", "Binary search optimization: maintain a list of smallest tail elements."]', 'Very Common', 'Feb 2025', 156, true),
('Swiggy', 'https://logo.clearbit.com/swiggy.com', 'Easy', 'DSA', 'Strings', 'Check if a string is a valid palindrome considering only alphanumeric characters.', 'Two pointers from both ends. Skip non-alphanumeric characters. Compare lowercase versions. Time: O(n), Space: O(1).', '["Use two pointers: one from start, one from end.", "Skip non-alphanumeric characters.", "Compare characters case-insensitively."]', 'Very Common', 'Mar 2025', 45, true),
('Swiggy', 'https://logo.clearbit.com/swiggy.com', 'Medium', 'Backend', 'Caching', 'How would you implement a cache invalidation strategy for a food delivery menu that changes frequently?', 'TTL-based expiration (5-10 min for menus). Write-through cache: update cache on every DB write. Pub/Sub for cache invalidation across instances. Cache-aside pattern for reads. Tags/keys per restaurant for selective invalidation. Stale-while-revalidate for better UX.', '["Cache invalidation is one of the hardest problems in CS.", "When a restaurant updates their menu, how do all cache instances know?", "Consider TTL vs event-driven invalidation — what are the trade-offs?"]', 'Common', 'Feb 2025', 89, true),
('Swiggy', 'https://logo.clearbit.com/swiggy.com', 'Medium', 'DSA', 'Hashing', 'Find the length of the longest consecutive sequence in an unsorted array.', 'Use a HashSet. For each number, check if it''s the start of a sequence (num-1 not in set). If so, count consecutive numbers from there. Time: O(n), Space: O(n).', '["Insert all numbers into a HashSet.", "For each number, check if it starts a sequence (num-1 not present).", "Only start counting from sequence beginnings to avoid repeated work."]', 'Very Common', 'Mar 2025', 134, true),
('Swiggy', 'https://logo.clearbit.com/swiggy.com', 'Medium', 'DSA', 'Trees', 'Level order traversal of a binary tree (BFS).', 'Use a queue. Start with root. For each level, process all nodes in queue, adding their children. Store each level as a separate list. Time: O(n), Space: O(n).', '["BFS naturally processes level by level.", "Use a queue — process current level size nodes, then move to next.", "Track level boundaries by recording queue size at each level start."]', 'Very Common', 'Mar 2025', 56, true),
('Swiggy', 'https://logo.clearbit.com/swiggy.com', 'Medium', 'Backend', 'System Design', 'Design a notification preference system where users can set preferences per channel per notification type.', 'Schema: user_notification_preferences(user_id, notification_type, channel, enabled). Notification types: order_update, promo, review_reminder. Channels: push, sms, email. Default preferences per type. Override per user. Check preferences before sending. Batch preference updates. Cache active preferences in Redis.', '["Users want granular control — per notification type AND per channel.", "Design a schema that supports defaults and user overrides.", "How do you efficiently check preferences at notification send time?"]', 'Common', 'Jan 2025', 78, true);

-- CRED (10 questions)
INSERT INTO company_questions (company, company_logo_url, difficulty, category, topic, question_text, expected_answer, hints, frequency, last_seen, upvotes, is_verified) VALUES
('CRED', 'https://logo.clearbit.com/cred.club', 'Medium', 'DSA', 'Arrays', 'Given an array, find the next greater element for each element using a stack.', 'Use a monotonic decreasing stack. Traverse right to left: pop elements smaller than current (they found their NGE). Push current. For remaining stack elements, NGE is -1. Time: O(n), Space: O(n).', '["A stack can efficiently find the next greater element.", "Traverse from right to left, maintaining a decreasing stack.", "Pop elements smaller than current — current is their next greater."]', 'Very Common', 'Mar 2025', 112, true),
('CRED', 'https://logo.clearbit.com/cred.club', 'Medium', 'Frontend', 'React', 'Explain the React reconciliation algorithm (Virtual DOM diffing). How does React decide what to re-render?', 'React creates a Virtual DOM tree. On state change, it creates a new tree and diffs against the old one (reconciliation). Key assumptions: different types = different trees (replace entire subtree), keys identify stable elements in lists. Fiber architecture enables incremental rendering with priorities.', '["React compares old and new Virtual DOM trees.", "Two heuristics: different types = new subtree, keys identify list items.", "Fiber architecture breaks rendering into interruptible units of work."]', 'Very Common', 'Feb 2025', 156, true),
('CRED', 'https://logo.clearbit.com/cred.club', 'Hard', 'DSA', 'Dynamic Programming', 'Given a string of digits, count the number of ways to decode it (A=1, B=2, ..., Z=26).', 'DP: dp[i] = ways to decode s[0..i-1]. dp[i] += dp[i-1] if s[i-1] is valid single digit (1-9). dp[i] += dp[i-2] if s[i-2..i-1] is valid two-digit (10-26). Base: dp[0]=1, dp[1]=1 if s[0]!=''0''. Time: O(n).', '["Each digit can be decoded alone (1-9) or as part of a two-digit number (10-26).", "dp[i] = number of ways to decode the first i characters.", "Handle edge case: ''0'' cannot be decoded alone."]', 'Common', 'Jan 2025', 89, true),
('CRED', 'https://logo.clearbit.com/cred.club', 'Medium', 'Frontend', 'JavaScript', 'Implement a debounce function in JavaScript.', 'function debounce(fn, delay) { let timer; return function(...args) { clearTimeout(timer); timer = setTimeout(() => fn.apply(this, args), delay); }; } Clears previous timer on each call, only executes after delay ms of inactivity.', '["Debounce delays execution until input stops for a specified duration.", "Clear the previous timer on each new call.", "Use setTimeout and clearTimeout to manage the delay."]', 'Very Common', 'Mar 2025', 178, true),
('CRED', 'https://logo.clearbit.com/cred.club', 'Medium', 'DSA', 'Trees', 'Find the diameter of a binary tree (longest path between any two nodes).', 'DFS returning height at each node. Diameter at each node = left_height + right_height. Track global max. Time: O(n), Space: O(h). The diameter may or may not pass through the root.', '["Diameter is the longest path between any two nodes in the tree.", "At each node, the longest path through it = left height + right height.", "The diameter may not pass through the root — check every node."]', 'Very Common', 'Feb 2025', 134, true),
('CRED', 'https://logo.clearbit.com/cred.club', 'Hard', 'Frontend', 'Performance', 'How would you optimize the performance of a React application that renders 10,000+ list items?', 'Use virtualization (react-window/react-virtualized) to render only visible items. React.memo to prevent unnecessary re-renders. useMemo/useCallback for expensive computations. Pagination or infinite scroll. Web Workers for heavy computation. Code splitting with React.lazy. Avoid inline objects/functions in render.', '["Rendering 10K DOM nodes is expensive — how do you render only what''s visible?", "Virtualization libraries render only items in the viewport.", "Prevent re-renders with React.memo, useMemo, and proper key usage."]', 'Common', 'Jan 2025', 123, true),
('CRED', 'https://logo.clearbit.com/cred.club', 'Medium', 'DSA', 'Arrays', 'Find all pairs in an array that sum to a given target. Handle duplicates.', 'Sort array. Use two pointers (left, right). If sum equals target, add pair and skip duplicates by advancing both pointers past same values. If sum < target, move left. If sum > target, move right. Time: O(n log n).', '["Sort the array first for an efficient two-pointer approach.", "After finding a pair, skip duplicates by advancing past same values.", "Two pointers converge from both ends — left for smaller, right for larger."]', 'Common', 'Feb 2025', 67, true),
('CRED', 'https://logo.clearbit.com/cred.club', 'Medium', 'Frontend', 'CSS', 'Explain CSS specificity rules and how the cascade determines which styles apply.', 'Specificity hierarchy: inline styles (1000) > IDs (100) > classes/attributes/pseudo-classes (10) > elements/pseudo-elements (1). !important overrides all. Equal specificity: last declaration wins. Inheritance passes some properties to children. The cascade: importance → specificity → source order.', '["Specificity is calculated as a 4-part score: inline, ID, class, element.", "Higher specificity always wins regardless of source order.", "!important breaks the normal cascade — use sparingly."]', 'Common', 'Jan 2025', 78, true),
('CRED', 'https://logo.clearbit.com/cred.club', 'Easy', 'DSA', 'Strings', 'Implement a function to check if two strings are one edit distance apart (insert, delete, or replace one character).', 'If lengths differ by >1, return false. If same length, count differences — must be exactly 1 (replace). If lengths differ by 1, try inserting into shorter — characters must match after the edit. Time: O(n).', '["Three possible edits: insert, delete, replace.", "If lengths are equal, check for exactly one different character.", "If lengths differ by 1, check if removing one character makes them equal."]', 'Common', 'Feb 2025', 56, true),
('CRED', 'https://logo.clearbit.com/cred.club', 'Medium', 'Frontend', 'React', 'What are React hooks rules? Explain useState, useEffect, useCallback, and useMemo with examples.', 'Rules: only call at top level (not in loops/conditions), only call in React functions. useState: manages state. useEffect: side effects (API calls, subscriptions), cleanup function for unmount. useCallback: memoize function reference. useMemo: memoize computed value. Both prevent unnecessary recalculations.', '["Hooks must be called at top level — no conditional hooks.", "useEffect runs after render — think of it as componentDidMount + componentDidUpdate.", "useCallback memoizes functions, useMemo memoizes values — both take dependency arrays."]', 'Very Common', 'Mar 2025', 167, true);

-- RAZORPAY (15 questions)
INSERT INTO company_questions (company, company_logo_url, difficulty, category, topic, question_text, expected_answer, hints, frequency, last_seen, upvotes, is_verified) VALUES
('Razorpay', 'https://logo.clearbit.com/razorpay.com', 'Medium', 'DSA', 'Arrays', 'Given an array of stock prices, find the maximum profit you can make by buying and selling once.', 'Track min_price and max_profit. For each price: update min_price = min(min_price, price), then max_profit = max(max_profit, price - min_price). Time: O(n), Space: O(1).', '["You need to buy before you sell.", "Track the minimum price seen so far.", "At each price, calculate potential profit = current - minimum."]', 'Very Common', 'Mar 2025', 187, true),
('Razorpay', 'https://logo.clearbit.com/razorpay.com', 'Hard', 'System Design', 'System Design', 'Design a payment gateway system like Razorpay that handles 10,000 transactions per second.', 'Microservices: API Gateway → Order Service → Payment Processor → Bank Integration. Use message queue for async processing. Idempotency keys for duplicate prevention. Circuit breakers for bank API failures. ACID transactions for financial operations. PCI DSS compliance. Multi-region deployment for availability.', '["How do you ensure no money is lost during processing failures?", "Idempotency is critical — how do you prevent double charges?", "What happens when a bank''s API goes down during peak load?"]', 'Very Common', 'Feb 2025', 234, true),
('Razorpay', 'https://logo.clearbit.com/razorpay.com', 'Medium', 'DSA', 'Dynamic Programming', 'Longest Common Subsequence of two strings.', 'DP: dp[i][j] = LCS of s1[0..i-1] and s2[0..j-1]. If s1[i-1] == s2[j-1]: dp[i][j] = dp[i-1][j-1] + 1. Else: dp[i][j] = max(dp[i-1][j], dp[i][j-1]). Time: O(m*n), Space: O(m*n), optimizable to O(min(m,n)).', '["Compare characters at corresponding positions.", "If they match, extend the previous LCS by 1.", "If they don''t match, take the max of skipping either character."]', 'Common', 'Jan 2025', 112, true),
('Razorpay', 'https://logo.clearbit.com/razorpay.com', 'Medium', 'System Design', 'System Design', 'Design a reconciliation system that matches transactions between Razorpay records and bank statements.', 'Batch processing: import bank statements daily. Match by transaction ID, amount, date with fuzzy matching for dates. Categories: matched, unmatched (present in one side only), mismatched (amount differs). Dashboard for manual resolution. Alerting for high mismatch rates. Audit trail for all resolutions.', '["Reconciliation matches internal records with external bank data.", "Not all transactions will match perfectly — how do you handle discrepancies?", "Think about the data pipeline: how do you import, parse, and match records?"]', 'Common', 'Jan 2025', 98, true),
('Razorpay', 'https://logo.clearbit.com/razorpay.com', 'Easy', 'DSA', 'Hashing', 'Find if there exists a subarray with sum equal to zero.', 'Compute prefix sums. If any prefix sum repeats or equals zero, a zero-sum subarray exists. Use a HashSet to track seen prefix sums. Time: O(n), Space: O(n).', '["Prefix sum helps identify subarray sums.", "If prefix_sum[i] == prefix_sum[j], then sum of subarray [i+1..j] is 0.", "Also check if any prefix sum itself is 0 (subarray from start)."]', 'Very Common', 'Mar 2025', 78, true),
('Razorpay', 'https://logo.clearbit.com/razorpay.com', 'Hard', 'DSA', 'Graphs', 'Find the number of islands in a 2D grid (connected components of 1s).', 'DFS/BFS from each unvisited ''1''. Mark all connected ''1''s as visited. Count number of DFS/BFS calls initiated. Time: O(m*n), Space: O(m*n) for visited array/recursion.', '["Each island is a connected component of ''1'' cells.", "Traverse the grid — start DFS/BFS from each unvisited ''1''.", "Each new DFS/BFS call represents a new island."]', 'Very Common', 'Feb 2025', 167, true),
('Razorpay', 'https://logo.clearbit.com/razorpay.com', 'Medium', 'System Design', 'System Design', 'Design a webhook delivery system with guaranteed at-least-once delivery.', 'Queue-based: store webhook events in persistent queue (Kafka/SQS). Worker processes events: send HTTP POST, check response. If failure/timeout: exponential backoff retry (1s, 2s, 4s, 8s up to 24h). Dead letter queue after max retries. Idempotency: include event ID. Dashboard showing delivery status. Signature verification for security.', '["How do you handle the case where the merchant''s server is down?", "Exponential backoff prevents overwhelming failing endpoints.", "How does the merchant know the webhook is authentic and from you?"]', 'Common', 'Feb 2025', 123, true),
('Razorpay', 'https://logo.clearbit.com/razorpay.com', 'Medium', 'DSA', 'Trees', 'Construct a binary tree from inorder and preorder traversals.', 'Preorder first element is root. Find root in inorder — elements left of it form left subtree, right form right subtree. Recursively build. Use a HashMap for O(1) root lookup in inorder. Time: O(n).', '["First element of preorder is always the root.", "Find root in inorder — it splits left and right subtrees.", "Recurse with correct slices of both arrays."]', 'Common', 'Jan 2025', 89, true),
('Razorpay', 'https://logo.clearbit.com/razorpay.com', 'Hard', 'System Design', 'System Design', 'Design a fraud detection system for payment transactions in real-time.', 'ML pipeline: feature engineering (velocity checks, device fingerprint, geolocation, amount patterns), real-time scoring using a pre-trained model. Rules engine for known fraud patterns. Stream processing (Kafka Streams/Flink) for real-time signals. Risk score → approve/review/block. Human review queue for medium-risk. Feedback loop to retrain model.', '["What signals indicate potentially fraudulent transactions?", "How do you balance fraud prevention with false positive rate?", "Real-time scoring must be fast — what''s the latency budget?"]', 'Rare', 'Dec 2024', 145, true),
('Razorpay', 'https://logo.clearbit.com/razorpay.com', 'Medium', 'DSA', 'Arrays', 'Implement next permutation — rearrange numbers into the lexicographically next greater permutation.', 'From right, find first decreasing element (i). From right, find first element greater than nums[i] (j). Swap nums[i] and nums[j]. Reverse the suffix after i. Time: O(n), Space: O(1).', '["Scan from right to find the first pair where nums[i] < nums[i+1].", "Find the smallest number greater than nums[i] to the right of i.", "After swapping, reverse the suffix to get the smallest next permutation."]', 'Common', 'Feb 2025', 98, true),
('Razorpay', 'https://logo.clearbit.com/razorpay.com', 'Easy', 'DSA', 'Strings', 'Check if a given string of parentheses is balanced.', 'Use a stack. Push open brackets. On close bracket, check if stack top is matching open — if yes, pop; else invalid. At end, stack should be empty. Time: O(n), Space: O(n).', '["Use a stack to match opening and closing brackets.", "Push opening brackets, pop on matching closing brackets.", "Final stack must be empty for valid parentheses."]', 'Very Common', 'Mar 2025', 56, true),
('Razorpay', 'https://logo.clearbit.com/razorpay.com', 'Medium', 'DSA', 'Matrix', 'Rotate a matrix 90 degrees clockwise in-place.', 'Transpose the matrix (swap rows and columns), then reverse each row. For counter-clockwise: reverse each row first, then transpose. Time: O(n²), Space: O(1).', '["Break the rotation into two simpler operations.", "Transpose: swap matrix[i][j] with matrix[j][i].", "Then reverse each row to complete the 90-degree rotation."]', 'Common', 'Feb 2025', 78, true),
('Razorpay', 'https://logo.clearbit.com/razorpay.com', 'Medium', 'System Design', 'System Design', 'Design an auto-retry mechanism with exponential backoff for failed API calls.', 'Retry with delays: 1s, 2s, 4s, 8s (exponential). Add jitter (random 0-1s) to prevent thundering herd. Max retries cap (e.g., 5). Retry only on retriable errors (5xx, timeout, not 4xx). Circuit breaker to stop retries when endpoint is down. Log all retry attempts for debugging.', '["Exponential backoff: delay doubles with each retry.", "Jitter prevents all clients retrying simultaneously.", "Not all errors should be retried — distinguish 4xx from 5xx."]', 'Very Common', 'Mar 2025', 112, true),
('Razorpay', 'https://logo.clearbit.com/razorpay.com', 'Hard', 'DSA', 'Dynamic Programming', 'Edit Distance: Find minimum operations (insert, delete, replace) to convert string A to string B.', 'DP: dp[i][j] = min edits to convert A[0..i-1] to B[0..j-1]. If A[i-1]==B[j-1]: dp[i][j] = dp[i-1][j-1]. Else: dp[i][j] = 1 + min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1]) for delete, insert, replace. Time: O(m*n).', '["dp[i][j] = minimum edits for first i chars of A and first j chars of B.", "If characters match, no edit needed — take diagonal value.", "Otherwise, try all three operations and take the minimum."]', 'Common', 'Jan 2025', 134, true),
('Razorpay', 'https://logo.clearbit.com/razorpay.com', 'Medium', 'DSA', 'Graphs', 'Detect a cycle in an undirected graph.', 'DFS with parent tracking. If during DFS you visit a node that''s already visited and isn''t the parent of the current node, a cycle exists. Alternatively, use Union-Find: if two nodes of an edge are already in the same set, cycle exists. Time: O(V+E).', '["In DFS, a back edge to a non-parent visited node indicates a cycle.", "Union-Find: if adding an edge connects two already-connected nodes, there''s a cycle.", "Handle disconnected graphs by running from all unvisited nodes."]', 'Common', 'Feb 2025', 89, true);
