-- ============================================================
-- SEED Part 5: Microsoft (15), Meta (15), Adobe (10)
-- ============================================================

-- MICROSOFT (15 questions)
INSERT INTO company_questions (company, company_logo_url, difficulty, category, topic, question_text, expected_answer, hints, frequency, last_seen, upvotes, is_verified) VALUES
('Microsoft', 'https://logo.clearbit.com/microsoft.com', 'Medium', 'DSA', 'Arrays', 'Find the majority element (appears more than n/2 times). Prove correctness.', 'Boyer-Moore Voting: maintain candidate and count. If count=0, set new candidate. If same as candidate, count++, else count--. The candidate at the end is majority (verify with second pass). Time: O(n), Space: O(1).', '["The majority element occurs more than half the time.", "Boyer-Moore: the majority element survives all cancellations.", "Consider: why does the algorithm work? Think about canceling pairs."]', 'Very Common', 'Mar 2025', 156, true),
('Microsoft', 'https://logo.clearbit.com/microsoft.com', 'Medium', 'DSA', 'Trees', 'Convert a sorted array to a balanced Binary Search Tree.', 'Use the middle element as root. Recursively build left subtree from left half, right subtree from right half. This ensures O(log n) height. Time: O(n), Space: O(log n) stack.', '["Middle element becomes the root for balance.", "Left half forms left subtree, right half forms right subtree.", "Recursive: each subarray''s middle is the subtree root."]', 'Common', 'Feb 2025', 112, true),
('Microsoft', 'https://logo.clearbit.com/microsoft.com', 'Hard', 'System Design', 'System Design', 'Design Microsoft Teams — real-time messaging, video conferencing, and file sharing.', 'Messaging: WebSocket for real-time, message queue for offline delivery. Video: WebRTC for peer-to-peer (small calls), SFU (Selective Forwarding Unit) for large meetings. File sharing: Azure Blob Storage with CDN. Presence service: heartbeat-based online status. Notifications: push, email, in-app. End-to-end encryption.', '["Different features have different infrastructure needs.", "Video conferencing at scale needs media servers, not just P2P.", "How do you handle message ordering and delivery guarantees?"]', 'Very Common', 'Feb 2025', 234, true),
('Microsoft', 'https://logo.clearbit.com/microsoft.com', 'Medium', 'DSA', 'Strings', 'Implement strStr() — find the first occurrence of a substring (needle) in a string (haystack).', 'KMP algorithm: build failure function (partial match table). Use it to avoid re-checking matched characters. Time: O(n+m). Naive: O(n*m). Rabin-Karp: rolling hash for O(n) average.', '["Naive O(n*m) — can you avoid re-examining characters?", "KMP: the failure function tells you where to restart matching.", "Rolling hash (Rabin-Karp) enables O(1) substring comparison."]', 'Common', 'Jan 2025', 98, true),
('Microsoft', 'https://logo.clearbit.com/microsoft.com', 'Medium', 'DSA', 'Graphs', 'Detect a cycle in a directed graph using DFS.', 'Three-color DFS: White (unvisited), Gray (in current DFS path), Black (fully processed). If DFS encounters a Gray node, there''s a cycle (back edge). Time: O(V+E).', '["In directed graphs, only back edges indicate cycles.", "Use three states: unvisited, in-progress, completed.", "A back edge goes to a node that''s still in the current DFS path (gray)."]', 'Very Common', 'Mar 2025', 134, true),
('Microsoft', 'https://logo.clearbit.com/microsoft.com', 'Hard', 'DSA', 'Dynamic Programming', 'Burst Balloons: given n balloons with numbers, find maximum coins from bursting all.', 'DP on intervals: dp[i][j] = max coins from bursting balloons between i and j. For each k in [i,j], try k as the LAST balloon burst. dp[i][j] = max(dp[i][k-1] + nums[i-1]*nums[k]*nums[j+1] + dp[k+1][j]). Time: O(n³).', '["Think about which balloon to burst LAST, not first.", "If k is burst last between i and j, neighbors are i-1 and j+1.", "Interval DP: solve smaller intervals first, build up to larger."]', 'Rare', 'Nov 2024', 112, true),
('Microsoft', 'https://logo.clearbit.com/microsoft.com', 'Medium', 'System Design', 'System Design', 'Design an online collaborative document editor like Microsoft Word Online.', 'Operational Transform (OT) or CRDT for concurrent edits. WebSocket for real-time sync. Operations: insert, delete with position. Version vector for conflict resolution. Undo/redo stack per user. Auto-save with debounce. Rich text model: tree of blocks and inline styles.', '["Multiple users editing simultaneously — how do you merge changes?", "OT transforms operations against each other for consistency.", "CRDTs are conflict-free but more complex to implement."]', 'Common', 'Jan 2025', 167, true),
('Microsoft', 'https://logo.clearbit.com/microsoft.com', 'Medium', 'DSA', 'Arrays', 'Search in Rotated Sorted Array — find a target in O(log n).', 'Modified binary search: find which half is sorted. If target is in sorted half, search there. Otherwise, search the other half. Handle duplicates separately. Time: O(log n).', '["One half of the array is always sorted after rotation.", "Determine which half is sorted by comparing mid with endpoints.", "If target is in the sorted half, narrow search there; otherwise search the other half."]', 'Very Common', 'Mar 2025', 178, true),
('Microsoft', 'https://logo.clearbit.com/microsoft.com', 'Medium', 'DSA', 'Trees', 'Inorder successor in a BST.', 'If node has right subtree: successor is leftmost node in right subtree. Otherwise: traverse from root, tracking last left-turn ancestor. Time: O(h) where h is height.', '["If right subtree exists, successor is the leftmost node in it.", "If no right subtree, go up until you find an ancestor you''re in the left subtree of.", "From root: go right if node value ≥ target, go left and update potential successor."]', 'Common', 'Feb 2025', 89, true),
('Microsoft', 'https://logo.clearbit.com/microsoft.com', 'Hard', 'System Design', 'System Design', 'Design Azure Blob Storage — a massively scalable object storage service.', 'Flat namespace with containers. Data stored in extents (chunks). Extent nodes for storage, partition servers for metadata. Three replicas across fault domains. Erasure coding for cold data. Stream layer handles replication. Partition layer handles indexing and transactions. Garbage collection for deleted data.', '["How do you store and retrieve petabytes of data reliably?", "Replication across fault domains ensures availability.", "Cold vs hot data may use different storage strategies."]', 'Rare', 'Nov 2024', 145, true),
('Microsoft', 'https://logo.clearbit.com/microsoft.com', 'Medium', 'DSA', 'Linked Lists', 'Add two numbers represented as linked lists (digits in reverse order).', 'Traverse both lists simultaneously, adding digits + carry. Create new nodes for result. Handle different lengths and final carry. Time: O(max(m,n)), Space: O(max(m,n)).', '["Process both lists digit by digit, similar to manual addition.", "Don''t forget the carry at each step.", "Handle different-length lists and a final carry digit."]', 'Very Common', 'Mar 2025', 145, true),
('Microsoft', 'https://logo.clearbit.com/microsoft.com', 'Medium', 'DSA', 'Dynamic Programming', 'Unique Paths in a grid from top-left to bottom-right (only move right or down).', 'DP: dp[i][j] = dp[i-1][j] + dp[i][j-1]. Base: first row and first column all 1s. Time: O(m*n), Space: O(n) with 1D array. Also solvable with combinatorics: C(m+n-2, m-1).', '["Each cell can only be reached from above or from the left.", "dp[i][j] = number of paths to reach cell (i,j).", "First row and column have exactly 1 path each."]', 'Common', 'Feb 2025', 98, true),
('Microsoft', 'https://logo.clearbit.com/microsoft.com', 'Medium', 'DSA', 'Stacks', 'Daily Temperatures: given daily temperatures, find how many days until a warmer day for each.', 'Monotonic decreasing stack of indices. For each day, pop all indices with lower temperatures — their wait is current_index - popped_index. Push current index. Time: O(n).', '["A stack of indices helps track unresolved days.", "Pop when current temperature is higher than stack top.", "Days remaining in the stack at the end have no warmer day (answer = 0)."]', 'Common', 'Jan 2025', 112, true),
('Microsoft', 'https://logo.clearbit.com/microsoft.com', 'Medium', 'System Design', 'System Design', 'Design a notification system for Microsoft Outlook that handles email, calendar, and Teams notifications.', 'Unified notification service: ingests events from email, calendar, teams. Priority levels: urgent (call), high (meeting reminder), normal (email). Channels: push, desktop toast, badge count. User preferences per channel per source. Batching non-urgent notifications. Do-not-disturb schedule. Device sync.', '["Different notification types have different urgency levels.", "Users want granular control over what notifies them and how.", "How do you prevent notification overload while ensuring nothing important is missed?"]', 'Common', 'Feb 2025', 98, true),
('Microsoft', 'https://logo.clearbit.com/microsoft.com', 'Easy', 'DSA', 'Arrays', 'Move all zeroes to the end of array while maintaining relative order of non-zero elements.', 'Two-pointer: slow pointer tracks next non-zero position. Fast pointer scans. When fast finds non-zero, swap with slow position and advance slow. Time: O(n), Space: O(1).', '["Maintain a pointer for where the next non-zero should go.", "Scan left to right, swapping non-zero elements to the front.", "All elements after the slow pointer will be zeroes."]', 'Very Common', 'Mar 2025', 67, true);

-- META (15 questions)
INSERT INTO company_questions (company, company_logo_url, difficulty, category, topic, question_text, expected_answer, hints, frequency, last_seen, upvotes, is_verified) VALUES
('Meta', 'https://logo.clearbit.com/meta.com', 'Medium', 'DSA', 'Arrays', 'Given an array of meeting intervals, find the minimum number of conference rooms required.', 'Sort start and end times separately. Two pointers: if next event starts before current ends, need extra room. Track max concurrent meetings. Time: O(n log n). Or use min-heap sorted by end times.', '["Think of it as: how many meetings overlap at the peak?", "Sort start times and end times separately, sweep through.", "A min-heap tracking end times: if new meeting starts after heap top, reuse room."]', 'Very Common', 'Mar 2025', 198, true),
('Meta', 'https://logo.clearbit.com/meta.com', 'Hard', 'System Design', 'System Design', 'Design the Facebook News Feed — personalized content ranking for billions of users.', 'Fan-out on write (push to followers'' feeds) for normal users. Fan-out on read (pull) for celebrity users. Feed stored in Redis lists. Ranking service: ML model scoring posts by relevance (engagement prediction, recency, relationship). Mixed media: text, images, video, links. Real-time updates via long polling/WebSocket.', '["Fan-out on write vs read: different strategies for different user types.", "Ranking: how do you score posts for relevance to each user?", "How do you handle a user with 10M followers posting?"]', 'Very Common', 'Feb 2025', 289, true),
('Meta', 'https://logo.clearbit.com/meta.com', 'Medium', 'DSA', 'Graphs', 'Given a list of accounts with names and emails, merge accounts belonging to the same person.', 'Model as graph: emails as nodes, edges between emails in same account. Find connected components using Union-Find or DFS. Group emails by component and associate with name. Time: O(n * α(n)) with Union-Find.', '["Two accounts belong to the same person if they share any email.", "Build a graph connecting emails within each account.", "Connected components in this graph represent unique people."]', 'Very Common', 'Mar 2025', 167, true),
('Meta', 'https://logo.clearbit.com/meta.com', 'Medium', 'DSA', 'Trees', 'Binary Tree Right Side View — return values visible from the right side.', 'BFS level-order, take last node of each level. Or DFS: visit right subtree before left, first node at each depth is the right view. Time: O(n).', '["Level order traversal: the last node at each level is visible from the right.", "DFS approach: go right first, track the first node at each new depth.", "Both approaches are O(n) — BFS is more intuitive."]', 'Common', 'Feb 2025', 123, true),
('Meta', 'https://logo.clearbit.com/meta.com', 'Hard', 'DSA', 'Dynamic Programming', 'Decode Ways: given a string of digits, count the number of ways to decode it.', 'DP: dp[i] = ways to decode first i chars. Single digit (1-9): dp[i] += dp[i-1]. Two digits (10-26): dp[i] += dp[i-2]. Handle ''0'' — can only be part of 10 or 20. Time: O(n), Space: O(1).', '["Each digit can be decoded alone or as part of a two-digit number.", "''0'' cannot be decoded alone — it must be part of 10 or 20.", "dp[i] depends on one-digit and two-digit decodings ending at position i."]', 'Very Common', 'Mar 2025', 145, true),
('Meta', 'https://logo.clearbit.com/meta.com', 'Medium', 'System Design', 'System Design', 'Design Facebook Messenger — real-time messaging with group chats and media sharing.', 'WebSocket for real-time delivery. Message queue for offline users. Chat service: create/join groups, send/receive messages. Media: upload to CDN, share URL. Read receipts: track per-user last-read timestamp. Encryption: end-to-end for private chats. Message storage: sorted by timestamp, paginated retrieval.', '["Real-time delivery requires persistent connections (WebSocket).", "How do you handle messages when the recipient is offline?", "Group chats: fan-out message to all members, track read receipts per member."]', 'Very Common', 'Feb 2025', 212, true),
('Meta', 'https://logo.clearbit.com/meta.com', 'Medium', 'DSA', 'Strings', 'Valid Palindrome II — can a string become a palindrome by removing at most one character?', 'Two pointers from both ends. On mismatch, check if skipping left or right makes the remaining substring a palindrome. Time: O(n), Space: O(1).', '["Start with standard palindrome check using two pointers.", "On first mismatch, you get one chance to skip a character.", "Check both possibilities: skip left char or skip right char."]', 'Very Common', 'Mar 2025', 134, true),
('Meta', 'https://logo.clearbit.com/meta.com', 'Medium', 'DSA', 'Arrays', 'Random Pick with Weight — pick an index proportional to its weight.', 'Build prefix sum array. Generate random number in [1, total_weight]. Binary search for the index in prefix sum array. Time: O(log n) per pick, O(n) preprocessing.', '["Prefix sums create ranges proportional to weights.", "Random number falls into a range — binary search for which.", "Larger weights get larger ranges, so they''re picked more often."]', 'Common', 'Feb 2025', 98, true),
('Meta', 'https://logo.clearbit.com/meta.com', 'Hard', 'DSA', 'Graphs', 'Alien Dictionary — given sorted words in an alien language, determine the character order.', 'Build directed graph from adjacent word pairs (first differing character gives an edge). Topological sort gives the character order. If cycle exists, no valid ordering. Handle edge case: prefix word after longer word = invalid.', '["Compare adjacent words to find character ordering constraints.", "First differing character in two adjacent words gives a directed edge.", "Topological sort of the constraint graph gives the alphabet order."]', 'Common', 'Jan 2025', 156, true),
('Meta', 'https://logo.clearbit.com/meta.com', 'Medium', 'System Design', 'System Design', 'Design Instagram Stories — ephemeral content that disappears after 24 hours.', 'Upload: media → CDN. Story metadata: user_id, media_url, created_at, expires_at. Feed: aggregate stories from followed users, sorted by recency. Viewer tracking: store view events. Expiration: TTL in Redis, background worker for cleanup. Highlights: user-curated stories that persist.', '["Stories expire after 24 hours — how do you handle cleanup?", "Story feed: aggregate from all followed users, ordered by recency.", "View tracking: how do you efficiently track who viewed each story?"]', 'Common', 'Jan 2025', 134, true),
('Meta', 'https://logo.clearbit.com/meta.com', 'Medium', 'DSA', 'Trees', 'Lowest Common Ancestor of a binary tree.', 'Recursive: if root is null or equals p or q, return root. Search left and right subtrees. If both return non-null, root is LCA. If only one returns non-null, that''s the LCA. Time: O(n).', '["If p and q are in different subtrees, current node is their LCA.", "If both are in the same subtree, LCA is deeper.", "Base case: if current node is p, q, or null — return it."]', 'Very Common', 'Mar 2025', 178, true),
('Meta', 'https://logo.clearbit.com/meta.com', 'Hard', 'DSA', 'Dynamic Programming', 'Longest Palindromic Subsequence.', 'DP: dp[i][j] = length of LPS in s[i..j]. If s[i]==s[j]: dp[i][j] = dp[i+1][j-1] + 2. Else: dp[i][j] = max(dp[i+1][j], dp[i][j-1]). Fill diagonally. Time: O(n²), Space: O(n²).', '["A subsequence doesn''t need to be contiguous.", "If endpoints match, they''re both in the LPS.", "If they don''t match, skip one of them and take the better result."]', 'Common', 'Jan 2025', 112, true),
('Meta', 'https://logo.clearbit.com/meta.com', 'Medium', 'DSA', 'Arrays', 'Interval List Intersections — find intersections between two sorted interval lists.', 'Two pointers, one per list. Intersection exists if max(start1, start2) <= min(end1, end2). Advance the pointer with smaller end time. Time: O(m+n).', '["Two sorted lists — use two pointers.", "Intersection = [max of starts, min of ends] if that''s a valid interval.", "Advance the pointer whose interval ends first."]', 'Common', 'Feb 2025', 89, true),
('Meta', 'https://logo.clearbit.com/meta.com', 'Hard', 'System Design', 'System Design', 'Design a real-time content moderation system for user-generated content at Facebook scale.', 'Multi-layer: automated ML models (image classification, NLP for text, video frame analysis) → confidence scoring → auto-remove high-confidence violations → human review queue for medium confidence. Real-time: process on upload before publishing. Appeals workflow. Feedback loop to improve models. Regional policy differences.', '["Content includes text, images, videos, links — different models for each.", "Balance between catching violations and minimizing false positives.", "How do you handle the scale of billions of posts per day?"]', 'Rare', 'Dec 2024', 167, true),
('Meta', 'https://logo.clearbit.com/meta.com', 'Medium', 'DSA', 'Graphs', 'Word Ladder: find shortest transformation sequence from beginWord to endWord, changing one letter at a time.', 'BFS: start from beginWord. At each level, try changing each character to a-z. If result is in wordList, add to queue and remove from list. First time we reach endWord, return depth. Time: O(n * L² * 26).', '["BFS guarantees shortest transformation path.", "At each step, try all single-letter changes.", "Use a set for wordList to enable O(1) lookup and prevent revisiting."]', 'Very Common', 'Mar 2025', 156, true);

-- ADOBE (10 questions)
INSERT INTO company_questions (company, company_logo_url, difficulty, category, topic, question_text, expected_answer, hints, frequency, last_seen, upvotes, is_verified) VALUES
('Adobe', 'https://logo.clearbit.com/adobe.com', 'Medium', 'DSA', 'Arrays', 'Given an unsorted array, find the contiguous subarray with the largest sum (Kadane''s algorithm).', 'Track current_max and global_max. current_max = max(nums[i], current_max + nums[i]). Update global_max at each step. Time: O(n), Space: O(1). Handle all-negative arrays by initializing with first element.', '["At each position, decide: extend current subarray or start new.", "current_max tracks best ending here, global_max tracks overall best.", "Initialize both with the first element to handle all-negative arrays."]', 'Very Common', 'Mar 2025', 134, true),
('Adobe', 'https://logo.clearbit.com/adobe.com', 'Medium', 'Frontend', 'React', 'Build a custom hook useDebounce that debounces a value with a specified delay.', 'function useDebounce(value, delay) { const [debounced, setDebounced] = useState(value); useEffect(() => { const timer = setTimeout(() => setDebounced(value), delay); return () => clearTimeout(timer); }, [value, delay]); return debounced; } Use for search inputs to reduce API calls.', '["Return a debounced version of the input value.", "useEffect with setTimeout and cleanup (clearTimeout).", "Dependency array should include value and delay."]', 'Very Common', 'Mar 2025', 156, true),
('Adobe', 'https://logo.clearbit.com/adobe.com', 'Medium', 'DSA', 'Trees', 'Zigzag (spiral) level order traversal of a binary tree.', 'BFS with level tracking. Alternate between left-to-right and right-to-left for each level. Use a deque: odd levels add to front, even levels add to back (or just reverse alternate levels). Time: O(n).', '["Standard BFS gives level order — you just need to alternate direction.", "Use a flag to track current direction, flip each level.", "Or simply reverse alternate levels of standard level-order result."]', 'Common', 'Feb 2025', 89, true),
('Adobe', 'https://logo.clearbit.com/adobe.com', 'Hard', 'Frontend', 'Performance', 'Explain how the browser renders a page. What are CRP (Critical Rendering Path) optimizations?', 'CRP: DOM construction → CSSOM construction → Render Tree → Layout → Paint → Composite. Optimizations: minimize critical resources (defer/async scripts), minimize critical bytes (minify, compress), minimize CRP length (inline critical CSS). Use code splitting. Lazy load images. Preload key assets. Avoid layout thrashing.', '["The browser must build DOM and CSSOM before rendering.", "Blocking resources (CSS, sync JS) delay rendering.", "Critical CSS inlining and async JS loading reduce time-to-first-paint."]', 'Common', 'Jan 2025', 134, true),
('Adobe', 'https://logo.clearbit.com/adobe.com', 'Medium', 'DSA', 'Dynamic Programming', 'Decode Ways — count the number of ways to decode a digit string into letters.', 'DP: dp[i] = dp[i-1] (if digit is 1-9) + dp[i-2] (if two digits form 10-26). Handle ''0'' specially — it can only be decoded as part of 10/20. Time: O(n), Space: O(1) with two variables.', '["''1'' through ''9'' can be single characters.", "''10'' through ''26'' can be two-character decodings.", "''0'' alone is invalid — it must be preceded by ''1'' or ''2''."]', 'Common', 'Feb 2025', 98, true),
('Adobe', 'https://logo.clearbit.com/adobe.com', 'Medium', 'Frontend', 'JavaScript', 'Explain event delegation in JavaScript. Why is it useful and how does it work?', 'Event delegation uses event bubbling: attach one event listener to a parent instead of multiple on children. The event object''s target tells which child was clicked. Benefits: fewer listeners (better memory), dynamically added children auto-handled, cleaner code. Use event.target and event.currentTarget.', '["Events bubble up from the target element through ancestors.", "Attach listener to parent, check event.target for which child triggered it.", "Especially useful for dynamic lists where children are added/removed."]', 'Very Common', 'Mar 2025', 112, true),
('Adobe', 'https://logo.clearbit.com/adobe.com', 'Medium', 'DSA', 'Graphs', 'Given a matrix of 0s and 1s, find the number of distinct islands (unique shapes).', 'DFS from each unvisited ''1''. Record the path/shape relative to the starting cell (direction sequence or relative coordinates). Use a Set of shapes. Two islands with same shape are counted once. Time: O(m*n).', '["Standard island counting but you need to track shapes.", "Record relative positions of each cell from the starting cell.", "Serialize the shape (set of relative coordinates) and use a HashSet."]', 'Rare', 'Nov 2024', 67, true),
('Adobe', 'https://logo.clearbit.com/adobe.com', 'Medium', 'Frontend', 'CSS', 'Implement a responsive grid layout that works across all screen sizes without media queries using CSS Grid.', 'Use CSS Grid with auto-fit/auto-fill and minmax: display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 1rem; This creates a responsive grid that automatically adjusts columns based on available space. auto-fit collapses empty tracks, auto-fill keeps them.', '["repeat(auto-fit, minmax(min, max)) creates responsive columns.", "minmax(250px, 1fr) — columns are at least 250px, grow to fill space.", "auto-fit vs auto-fill: auto-fit collapses empty tracks."]', 'Common', 'Feb 2025', 89, true),
('Adobe', 'https://logo.clearbit.com/adobe.com', 'Easy', 'DSA', 'Strings', 'Implement strStr() — find first occurrence of needle in haystack.', 'Sliding window: compare needle with each substring of haystack of same length. Return first match index, or -1. Time: O(n*m) naive, O(n+m) with KMP.', '["Slide a window of needle''s length across haystack.", "Compare character by character at each position.", "KMP algorithm optimizes by using a prefix function to skip characters."]', 'Very Common', 'Mar 2025', 56, true),
('Adobe', 'https://logo.clearbit.com/adobe.com', 'Medium', 'Frontend', 'React', 'Explain React Context API vs Redux. When would you choose each?', 'Context: built-in, good for static/rarely-changing global state (theme, auth, locale). No middleware. Re-renders all consumers on change. Redux: external library with middleware (thunk, saga), time-travel debugging, predictable state updates, selector-based re-renders. Choose Context for simple needs, Redux for complex state with frequent updates.', '["Context re-renders all consumers; Redux can optimize with selectors.", "Redux adds boilerplate but provides powerful dev tools and middleware.", "For small apps or simple global state, Context is sufficient."]', 'Very Common', 'Mar 2025', 134, true);
