-- ============================================================
-- SEED Part 3: Infosys, TCS, Wipro
-- ============================================================

-- INFOSYS (10 questions)
INSERT INTO company_questions (company, company_logo_url, difficulty, category, topic, question_text, expected_answer, hints, frequency, last_seen, upvotes, is_verified) VALUES
('Infosys', 'https://logo.clearbit.com/infosys.com', 'Easy', 'DSA', 'Arrays', 'Find the second largest element in an array without sorting.', 'Track largest and second_largest. Iterate once: if element > largest, update second=largest, largest=element. If element > second and element != largest, update second. Time: O(n).', '["You only need one pass through the array.", "Track two variables: largest and second largest.", "Be careful with the update order and duplicate values."]', 'Very Common', 'Mar 2025', 78, true),
('Infosys', 'https://logo.clearbit.com/infosys.com', 'Easy', 'DSA', 'Strings', 'Count the number of vowels and consonants in a string.', 'Iterate through string, check if each alphabetic character is in {a,e,i,o,u} (case-insensitive). Increment vowel or consonant counter accordingly. Skip non-alphabetic characters. Time: O(n).', '["Only count alphabetic characters, skip spaces and punctuation.", "Use a set of vowels for O(1) lookup.", "Handle both uppercase and lowercase."]', 'Very Common', 'Mar 2025', 34, true),
('Infosys', 'https://logo.clearbit.com/infosys.com', 'Medium', 'DSA', 'Sorting', 'Implement binary search on a sorted array. What is its time complexity?', 'Set low=0, high=n-1. While low <= high: mid = low + (high-low)/2. If arr[mid] == target, return mid. If arr[mid] < target, low = mid+1. Else high = mid-1. Time: O(log n), Space: O(1).', '["Binary search eliminates half the search space each step.", "Use mid = low + (high - low) / 2 to avoid integer overflow.", "Return -1 if low > high — element not found."]', 'Very Common', 'Mar 2025', 89, true),
('Infosys', 'https://logo.clearbit.com/infosys.com', 'Easy', 'HR', 'Behavioral', 'Tell me about yourself and why you want to join Infosys.', 'Structure: Brief background → education → relevant skills/projects → why Infosys (global reach, training programs like InfyTQ, industry leader in digital transformation, career growth). Show enthusiasm for learning and contributing to large-scale enterprise projects.', '["Start with a brief professional summary, not personal history.", "Connect your skills to what Infosys does.", "Mention specific Infosys initiatives that excite you."]', 'Very Common', 'Mar 2025', 45, true),
('Infosys', 'https://logo.clearbit.com/infosys.com', 'Easy', 'DSA', 'OOP', 'Explain the four pillars of Object-Oriented Programming with examples.', 'Encapsulation: bundling data with methods, access modifiers (private fields, public getters). Inheritance: child class extends parent, code reuse. Polymorphism: same interface, different implementations (method overloading/overriding). Abstraction: hiding complexity, showing only essential features (abstract classes, interfaces).', '["Think of each pillar with a real-world analogy.", "Encapsulation: a capsule containing medicine (data) with controlled access.", "Polymorphism: same method name behaving differently based on the object type."]', 'Very Common', 'Mar 2025', 67, true),
('Infosys', 'https://logo.clearbit.com/infosys.com', 'Medium', 'DSA', 'DBMS', 'Explain normalization in databases. What are 1NF, 2NF, and 3NF?', '1NF: atomic values, no repeating groups. 2NF: 1NF + no partial dependencies (every non-key attribute depends on the full primary key). 3NF: 2NF + no transitive dependencies (non-key attributes don''t depend on other non-key attributes). Normalization reduces redundancy but may increase joins.', '["Each normal form builds on the previous one.", "1NF: each cell has a single value, each row is unique.", "2NF and 3NF deal with types of functional dependencies."]', 'Very Common', 'Feb 2025', 98, true),
('Infosys', 'https://logo.clearbit.com/infosys.com', 'Easy', 'HR', 'Behavioral', 'Where do you see yourself in 5 years?', 'Show ambition aligned with the company: growing from a developer to a technical lead, gaining expertise in a domain, contributing to bigger projects, mentoring juniors. Mention continuous learning and certification goals. Avoid answers that suggest leaving the company soon.', '["Show growth ambition within the company, not outside it.", "Mention specific skills or roles you want to develop.", "Balance between ambitious and realistic goals."]', 'Very Common', 'Mar 2025', 34, true),
('Infosys', 'https://logo.clearbit.com/infosys.com', 'Medium', 'DSA', 'OS', 'Explain the difference between process and thread. What is a deadlock?', 'Process: independent execution unit with own memory space. Thread: lightweight, shares memory within a process. Deadlock: circular dependency where processes wait for each other''s resources. Four conditions: mutual exclusion, hold and wait, no preemption, circular wait. Prevent by breaking any condition.', '["Processes are isolated, threads share memory within a process.", "Deadlock requires all four Coffman conditions simultaneously.", "Prevention strategies: resource ordering, timeouts, or acquiring all resources at once."]', 'Very Common', 'Feb 2025', 112, true),
('Infosys', 'https://logo.clearbit.com/infosys.com', 'Easy', 'DSA', 'Arrays', 'Remove duplicates from a sorted array in-place.', 'Two-pointer approach: slow pointer for position of next unique element, fast pointer scans. When arr[fast] != arr[slow], increment slow and copy. Return slow + 1 as new length. Time: O(n), Space: O(1).', '["Since the array is sorted, duplicates are adjacent.", "Use two pointers: one for writing position, one for reading.", "Copy only when a new unique element is found."]', 'Very Common', 'Mar 2025', 56, true),
('Infosys', 'https://logo.clearbit.com/infosys.com', 'Easy', 'HR', 'Behavioral', 'Describe a challenging project you worked on and what you learned.', 'Use STAR format: describe the project (Situation), your role and challenges (Task), specific actions you took to overcome them (Action), and the outcome with measurable results and learnings (Result). Focus on problem-solving skills, teamwork, and technical growth.', '["Use the STAR format for a structured answer.", "Focus on what YOU specifically did, not the team.", "End with concrete learnings and how they shaped your growth."]', 'Very Common', 'Mar 2025', 45, true);

-- TCS (10 questions)
INSERT INTO company_questions (company, company_logo_url, difficulty, category, topic, question_text, expected_answer, hints, frequency, last_seen, upvotes, is_verified) VALUES
('TCS', 'https://logo.clearbit.com/tcs.com', 'Easy', 'DSA', 'Arrays', 'Find the missing number in an array of 1 to N.', 'Expected sum = N*(N+1)/2. Actual sum = sum of array. Missing = Expected - Actual. Time: O(n), Space: O(1). Alternative: XOR all numbers 1..N with all array elements.', '["The sum of numbers 1 to N has a formula.", "Compare expected sum with actual sum of array.", "The difference is the missing number."]', 'Very Common', 'Mar 2025', 67, true),
('TCS', 'https://logo.clearbit.com/tcs.com', 'Easy', 'DSA', 'Strings', 'Reverse a string without using built-in reverse function.', 'Two-pointer swap: swap characters at left and right indices, move them towards center. Time: O(n), Space: O(1) if modifying char array in-place.', '["Use two pointers from both ends.", "Swap characters at left and right positions.", "Move inward until pointers meet in the middle."]', 'Very Common', 'Mar 2025', 45, true),
('TCS', 'https://logo.clearbit.com/tcs.com', 'Easy', 'DSA', 'Recursion', 'Write a recursive function to calculate the Nth Fibonacci number. Optimize it.', 'Naive recursion: fib(n) = fib(n-1) + fib(n-2), Time: O(2^n). Memoization: store computed values, Time: O(n), Space: O(n). Bottom-up DP with two variables: Time: O(n), Space: O(1).', '["Simple recursion has exponential time due to repeated subproblems.", "Memoization stores previously computed values to avoid recomputation.", "Bottom-up approach: just track the last two values."]', 'Very Common', 'Mar 2025', 56, true),
('TCS', 'https://logo.clearbit.com/tcs.com', 'Easy', 'HR', 'Behavioral', 'Why should we hire you? What makes you different from other candidates?', 'Highlight unique strengths: specific technical skills, relevant project experience, quick learning ability, team collaboration, passion for technology. Reference achievements with numbers. Show how your background directly addresses what TCS needs. Be confident but not arrogant.', '["Connect your strengths to the job requirements.", "Give specific examples, not generic claims.", "Show what unique value you bring to the team."]', 'Very Common', 'Mar 2025', 56, true),
('TCS', 'https://logo.clearbit.com/tcs.com', 'Medium', 'DSA', 'OOP', 'What is the difference between abstract class and interface in Java?', 'Abstract class: can have fields, constructors, both abstract and concrete methods, single inheritance. Interface: only abstract methods (before Java 8), multiple inheritance, default methods (Java 8+), static methods. Use abstract class for shared implementation, interface for contracts/capabilities.', '["Abstract classes can have state (fields), interfaces traditionally cannot.", "Java supports multiple interface inheritance but single class inheritance.", "Java 8+ allows default methods in interfaces, blurring the distinction."]', 'Very Common', 'Feb 2025', 78, true),
('TCS', 'https://logo.clearbit.com/tcs.com', 'Easy', 'DSA', 'Sorting', 'Explain the difference between Bubble Sort and Quick Sort. When would you use each?', 'Bubble Sort: compare adjacent, swap if needed, repeat. O(n²) time, O(1) space, stable. Good for nearly sorted small arrays. Quick Sort: partition around pivot, recurse on halves. O(n log n) average, O(n²) worst, O(log n) space, unstable. Best for general-purpose sorting.', '["Compare time complexity: O(n²) vs O(n log n) average.", "Bubble sort is simple but slow, Quick sort is fast but has a bad worst case.", "Consider stability — does the sort preserve order of equal elements?"]', 'Very Common', 'Mar 2025', 45, true),
('TCS', 'https://logo.clearbit.com/tcs.com', 'Easy', 'HR', 'Behavioral', 'Are you willing to relocate? How do you handle working in different time zones?', 'Express willingness and flexibility. Mention prior experience with diverse teams or environments. For time zones: discuss strategies like async communication, overlapping hours scheduling, and documentation. Show adaptability as a strength.', '["TCS is a global company — show willingness to work across geographies.", "Discuss specific strategies for remote/cross-timezone collaboration.", "Emphasize flexibility and adaptability as key strengths."]', 'Very Common', 'Mar 2025', 34, true),
('TCS', 'https://logo.clearbit.com/tcs.com', 'Medium', 'DSA', 'DBMS', 'Write a SQL query to find the second highest salary from an Employee table.', 'SELECT MAX(salary) FROM Employee WHERE salary < (SELECT MAX(salary) FROM Employee). Alternative: SELECT salary FROM Employee ORDER BY salary DESC LIMIT 1 OFFSET 1. Handle nulls and duplicates with DISTINCT.', '["First find the maximum salary, then find the max below that.", "Subquery approach: WHERE salary < MAX(salary).", "OFFSET approach: ORDER BY DESC, skip first result."]', 'Very Common', 'Feb 2025', 89, true),
('TCS', 'https://logo.clearbit.com/tcs.com', 'Medium', 'DSA', 'Networking', 'Explain the TCP/IP model layers and the difference between TCP and UDP.', 'TCP/IP layers: Application (HTTP, FTP), Transport (TCP, UDP), Internet (IP), Network Access (Ethernet). TCP: connection-oriented, reliable, ordered, flow control (3-way handshake). UDP: connectionless, unreliable, faster, no ordering. TCP for web/email, UDP for streaming/gaming.', '["TCP/IP has 4 layers vs OSI''s 7.", "TCP guarantees delivery with acknowledgments, UDP does not.", "Choose TCP for reliability, UDP for speed and real-time applications."]', 'Common', 'Feb 2025', 67, true),
('TCS', 'https://logo.clearbit.com/tcs.com', 'Easy', 'HR', 'Behavioral', 'How do you handle pressure and tight deadlines?', 'Describe your approach: prioritize tasks, break work into manageable chunks, communicate proactively about blockers, stay organized. Give a specific example where you delivered under pressure. Emphasize time management skills and remaining calm while focusing on solutions.', '["Give a specific example from experience.", "Show your process: prioritize, plan, execute, communicate.", "Focus on solutions, not stress — show resilience."]', 'Very Common', 'Mar 2025', 45, true);

-- WIPRO (10 questions)
INSERT INTO company_questions (company, company_logo_url, difficulty, category, topic, question_text, expected_answer, hints, frequency, last_seen, upvotes, is_verified) VALUES
('Wipro', 'https://logo.clearbit.com/wipro.com', 'Easy', 'DSA', 'Arrays', 'Check if an array is sorted in non-decreasing order.', 'Iterate from index 1 to n-1. If any arr[i] < arr[i-1], return false. If loop completes, return true. Time: O(n), Space: O(1).', '["Compare each element with its predecessor.", "If any element is smaller than the previous, it''s not sorted.", "An empty or single-element array is always sorted."]', 'Very Common', 'Mar 2025', 34, true),
('Wipro', 'https://logo.clearbit.com/wipro.com', 'Easy', 'DSA', 'Strings', 'Check if a given string is a pangram (contains all 26 English letters).', 'Create a set of lowercase letters from the string (only alphabetic chars). Check if set size >= 26. Time: O(n), Space: O(1) since set is bounded by 26.', '["A pangram contains all letters a-z.", "Use a set to track unique letters seen.", "Convert to lowercase before checking."]', 'Common', 'Feb 2025', 34, true),
('Wipro', 'https://logo.clearbit.com/wipro.com', 'Easy', 'DSA', 'Recursion', 'Calculate the factorial of a number using recursion and iteration.', 'Recursive: fact(n) = n * fact(n-1), base case fact(0) = 1. Iterative: result = 1, multiply result by i for i = 1 to n. Both Time: O(n). Recursive Space: O(n) stack, Iterative Space: O(1).', '["Base case: factorial of 0 is 1.", "Recursive: n * factorial(n-1).", "Iterative approach avoids stack overflow for large n."]', 'Very Common', 'Mar 2025', 45, true),
('Wipro', 'https://logo.clearbit.com/wipro.com', 'Easy', 'HR', 'Behavioral', 'What are your strengths and weaknesses?', 'Strengths: Give 2-3 specific, job-relevant strengths with examples (problem-solving, teamwork, quick learner). Weakness: Choose a genuine but non-critical weakness you''re actively improving (e.g., public speaking — enrolled in a speaking club). Show self-awareness and growth mindset.', '["Be specific — avoid generic strengths like ''hardworking''.", "For weaknesses, show self-awareness AND what you''re doing about it.", "Align strengths with the job requirements."]', 'Very Common', 'Mar 2025', 34, true),
('Wipro', 'https://logo.clearbit.com/wipro.com', 'Medium', 'DSA', 'OOP', 'Explain inheritance types in Java. What is the Diamond Problem?', 'Types: single, multilevel, hierarchical. Java doesn''t support multiple class inheritance. Diamond Problem: class D extends B and C, both extend A. If B and C override a method, D is ambiguous about which to use. Java solves this with interfaces + default methods, requiring explicit override.', '["Java supports single and multilevel inheritance for classes.", "Multiple inheritance of classes causes the Diamond Problem.", "Java allows multiple interface inheritance — resolving conflicts with explicit overrides."]', 'Common', 'Feb 2025', 56, true),
('Wipro', 'https://logo.clearbit.com/wipro.com', 'Easy', 'DSA', 'Arrays', 'Find the frequency of each element in an array.', 'Use a hash map: iterate array, increment count for each element. Print all key-value pairs. Time: O(n), Space: O(n). For sorted arrays, use a single pass counting consecutive equal elements.', '["Use a hash map to count occurrences.", "Iterate once, incrementing the count for each element.", "For sorted arrays, count consecutive equal elements."]', 'Very Common', 'Mar 2025', 34, true),
('Wipro', 'https://logo.clearbit.com/wipro.com', 'Easy', 'HR', 'Behavioral', 'Tell us about a time you worked in a team. What was your contribution?', 'STAR format: Situation (project context), Task (your role), Action (specific contributions — coding a module, resolving conflicts, coordinating), Result (project success, what you learned). Emphasize collaboration, communication, and taking initiative.', '["Focus on YOUR specific contribution, not general team success.", "Show how you collaborated, communicated, or resolved conflicts.", "Quantify the result if possible — delivered on time, improved metrics."]', 'Very Common', 'Mar 2025', 45, true),
('Wipro', 'https://logo.clearbit.com/wipro.com', 'Medium', 'DSA', 'Linked Lists', 'Find the middle element of a linked list in one pass.', 'Use slow and fast pointers. Slow moves one step, fast moves two steps. When fast reaches the end, slow is at the middle. Time: O(n), Space: O(1).', '["You can''t use length since you need to do it in one pass.", "Two pointers at different speeds solve this elegantly.", "When the fast pointer reaches the end, the slow pointer is at the middle."]', 'Very Common', 'Mar 2025', 67, true),
('Wipro', 'https://logo.clearbit.com/wipro.com', 'Medium', 'DSA', 'DBMS', 'What is the difference between INNER JOIN, LEFT JOIN, RIGHT JOIN, and FULL JOIN?', 'INNER JOIN: only matching rows from both tables. LEFT JOIN: all rows from left + matching from right (null if no match). RIGHT JOIN: all rows from right + matching from left. FULL JOIN: all rows from both (null where no match). Choose based on which rows you need to retain.', '["INNER JOIN is the intersection of both tables.", "LEFT JOIN keeps all left rows, filling nulls for unmatched right columns.", "FULL JOIN is the union — keeps everything from both sides."]', 'Very Common', 'Feb 2025', 78, true),
('Wipro', 'https://logo.clearbit.com/wipro.com', 'Easy', 'HR', 'Behavioral', 'How do you keep yourself updated with new technologies?', 'Mention specific sources: tech blogs (Medium, Dev.to), YouTube channels, online courses (Udemy, Coursera), reading documentation, contributing to open source, attending meetups or webinars, building personal projects. Show active learning with recent examples.', '["Name specific resources you actually use.", "Show a recent example of learning something new.", "Demonstrate continuous learning as a habit, not a one-time thing."]', 'Very Common', 'Mar 2025', 34, true);
